name: Build demo app

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  BuildAndroid:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Prepare Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      - name: Build demo app
        run: |
          cd example
          flutter build apk
      
      - name: Upload demo app APK to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: Flutter demo App
          path: example/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 14
